### PR TITLE
add start script

### PR DESCRIPTION
**Pull request by VadimDez**

### CODE REVIEW

**Comment by Anarcroth** [comment]
Hm, maybe I am missing something, but how are you adding a start script with the syntactical changes here?

**Comment by VadimDez** [comment]
I've added this line to `package.json` file 
```json
"start": "node server.js",
```

**Comment by Anarcroth** [comment]
Sorry mate, I don't want this change as of now and I don't think it serves any great benefit. Also if you want to refactor the README, then a separate issue has to be made for it, but I don't think that changing the syntax from `*` to `_` is that important.

**Comment by VadimDez** [comment]
maybe the title is misleading... but what I wanted to do is to add a npm script called `start` so that you don't need to type `node server.js`  or whatever you just type `nom start` to start your application.
I didn't want to change from `*` to `_` that was unintentional...

**Comment by Anarcroth** [comment]
Refactoring and re-writing tasks have to be separate :).
Anyhow, I understand that you wanted that start-script and granted, I've seen that many peolpe do that, but this is just such a small project. The start command is still `node server.js` and it's not a hassle to write. I'll think about it, but I closed the PR, cuz it's not something that's needed currently (maybe such a day will come).

**Pull request closed without merging**
